modLoader="javafml"
loaderVersion="[45,)"
license="Apache License version 2.0"

[[mods]]
modId="the_ender"
version="1.0.0"
displayName="The Ender+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gh5674"
description="Upgrades the end."

[[dependencies.the_ender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




